* dotfiles

This repository contains all the tools and configs that I like using on my computers.

I use Nix to replicate my environment on multiple OS.

** Apply configuration

1. Install nix with [[https://determinate.systems/nix-installer/][Determinate Nix installer]]

    Among other things, it will ask which version of Nix you want to install (i.e. official or Determinate).
    I suggest using official Nix on linux. Step 3 installs a package that is not compatible with
    Determinate Nix version.

    #+begin_src bash
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
    #+end_src

2. Install =just=

    #+begin_src bash
    nix profile install nixpkgs#just
    #+end_src

3. Apply configuration

    #+begin_src bash
    just build-config "config"
    #+end_src

    This will transparently install the tools required to apply the config on the current OS.

    On linux, this will install:

    - [[https://github.com/numtide/system-manager][System Manager]]

    On macos, this will install:

    - [[https://github.com/LnL7/nix-darwin][nix-darwin]]

4. (Only for Linux systems other than NixOS) Install graphics

    #+begin_src bash
    just build-config "config"
    #+end_src

    This installs [[https://github.com/soupglasses/nix-system-graphics][Nix System Graphics]]
    and it's required for GUI apps like ghostty.

That's it. When applying a configuration, take into account that some changes will only
take effect after you log out and log back in.

- Display GUI applications on the menu
- Activate the configured shell