#!/bin/bash

[[ $1 == "-h" || $1 == "--help" || -z $1 || -z $2 ]] \
	&& echo "USAGE: files-with-string [DIRECTORY] [SEARCH_STRING]" \
	&& echo -e "List all files in a directory which contain a specific string\n\n" \
	&& echo "First argument -> directory in which to search files" \
	&& echo "Second argument -> string to search in the file content" \
	&& exit

DIRECTORY=$1
STRING=$2

grep -r $DIRECTORY -e $STRING | cut -d : -f 1 | uniq | grep -v "Binary file" | sed -e "s/\.\///g" | sort
